### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-epub#112]
While running `./scripts/bake-book TEAhsphysics` in https://github.com/Connexions/cnx-rulesets I ran into this error

```
==> Validating ./data/TEAhsphysics-baked.xhtml
Traceback (most recent call last):
  File ".../cnx-recipes/venv/bin/cnx-epub-validate-collated", line 9, in <module>
    load_entry_point('cnx-epub==0.12.0', 'console_scripts', 'cnx-epub-validate-collated')()
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/scripts/collated_single_html/main.py", line 49, in main
    binder = reconstitute(args.collated_html)
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/adapters.py", line 356, in adapt_single_html
    _adapt_single_html_tree(binder, body[0], nav_tree)
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/adapters.py", line 487, in _adapt_single_html_tree
    id_map=id_map, depth=depth+1)
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/adapters.py", line 507, in _adapt_single_html_tree
    id_ = _compute_id(parent, child, metadata.get('title'))
  File ".../cnx-recipes/venv/lib/python2.7/site-packages/cnxepub/adapters.py", line 424, in _compute_id
    p_ids = [p.id.split('@')[0]]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
