### ISSUE TITLE
Implicit metadata requirements

### ISSUE THREAD

**Issue by BryanEliDimas** [openstax/cnx-epub#138]
While attempting to build the simplest kind of collection HTML file (a.k.a. "single HTML"), an exception was raised: `TypeError: expected string or buffer`. Eventually, I discovered that it was failing because metadata is a dictionary from which we try to get strings which will be used to build a jinja template after having built an `lxml.etree`. 

The problem is that IF the metadata does not contain one of the expected fields, a non-obvious exception is raised:

```
Traceback (most recent call last):
  File "/Users/bryaneli/Library/Python/2.7/lib/python/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/tests/test_formatters.py", line 767, in test_bryans_code
    SingleHTMLFormatter(binder)
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 206, in __init__
    self.root = etree.fromstring(bytes(HTMLFormatter(self.binder)))
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 195, in __str__
    return self.__bytes__()
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 198, in __bytes__
    html = self._template.render(self._template_args)
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 183, in _template_args
    'content': self._content,
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 150, in _content
    model_to_tree(self.model), self.extensions).decode('utf-8')
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 845, in tree_to_html
    html_listify(tree['contents'], ol, extensions)
  File "/Users/bryaneli/openstax/cnx-epub/cnxepub/formatters.py", line 829, in html_listify
    node['title'], create_parent='a')
  File "/usr/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 834, in fragment_fromstring
    base_url=base_url, **kw)
  File "/usr/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 793, in fragments_fromstring
    if not _looks_like_full_html_unicode(html):
TypeError: expected string or buffer
```

Although I have not yet used it, there seems to be a metadata parser which I presume we could use to make the required fields explicit in `html_parsers.DocumentMetadataParser`. If this is correct, I'd propose as a solution to this issue that we make it an explicit requirement to use that and then pass it in to `models.Document`, not a raw dictionary object. This would involve also fixing all of the tests that currently pass in a `base_metadata` dictionary.

**Comment by BryanEliDimas** [comment]
I found such function 😅. I suppose that all this information just needs to be made explicit in the tests!

https://github.com/openstax/cnx-epub/blob/d2c695513a34c4911507ca5144772693d7dc86e3/cnxepub/html_parsers.py#L81

**Comment by karenc** [comment]
That function parses the metadata from the single html, since you're building a `Document` yourself, you won't be able to use it.  I think what you pointed out in this issue is valid.  We expected some metadata to be there but it's not clear.  Why don't you try to fix this?
