### ISSUE TITLE
Error when fixing links while adapting from single HTML

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-epub#81]
```
ERROR:waitress:Exception when serving /contents/031da8d3-b525-429c-80cf-6c8ed997733a/collate-content
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/views/publishing.py", line 270, in collate_content
    collate(binder, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 86, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/collation.py", line 27, in collate
    binder = collate_models(binder)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 77, in collate
    collated_binder = reconstitute(collated_html)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 338, in adapt_single_html
    _adapt_single_html_tree(binder, body[0])
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 371, in _adapt_single_html_tree
    _adapt_single_html_tree(tbinder, child)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 394, in _adapt_single_html_tree
    fix_generated_ids(page, etree_)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/adapters.py", line 353, in fix_generated_ids
    target_page = page_id_to_page[page_id]
KeyError: u'102e9604-daa7-4a09-9f9e-232251d1a4ee'
```

**Comment by brittweinstein** [comment]
@karenc can this be closed with the existing single HTML work that is going on?

**Comment by karenc** [comment]
@brittweinstein No, the existing work doesn't touch this part of the code.  This was opened some time ago though, wonder if it's still a problem...

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
